CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_USB=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_IDLE_TIMEOUT=30000

# 0.91 inch I2C OLED: SCK/SCL=P0.20, SDA=P0.17, address 0x3C, usually 128x32.
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
